// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_dDJ-lFi9kUnQEdmuKVPjvZ5eWqbZzqs',
    appId: '1:113551519405:web:92b2e021e5d887dc1aa024',
    messagingSenderId: '113551519405',
    projectId: 'elbisikleta-5ffd8',
    authDomain: 'elbisikleta-5ffd8.firebaseapp.com',
    storageBucket: 'elbisikleta-5ffd8.firebasestorage.app',
    measurementId: 'G-3FTV898PLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6q280VpabF_x7u3dTQGC7n9qSeItMy8',
    appId: '1:113551519405:android:2ee228a9f7cb7edd1aa024',
    messagingSenderId: '113551519405',
    projectId: 'elbisikleta-5ffd8',
    storageBucket: 'elbisikleta-5ffd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecmMopfTs2-pv494JNEdnir3zsIBZ9G4',
    appId: '1:113551519405:ios:35530c4662fddf8d1aa024',
    messagingSenderId: '113551519405',
    projectId: 'elbisikleta-5ffd8',
    storageBucket: 'elbisikleta-5ffd8.firebasestorage.app',
    iosBundleId: 'com.example.elbisikleta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecmMopfTs2-pv494JNEdnir3zsIBZ9G4',
    appId: '1:113551519405:ios:35530c4662fddf8d1aa024',
    messagingSenderId: '113551519405',
    projectId: 'elbisikleta-5ffd8',
    storageBucket: 'elbisikleta-5ffd8.firebasestorage.app',
    iosBundleId: 'com.example.elbisikleta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_dDJ-lFi9kUnQEdmuKVPjvZ5eWqbZzqs',
    appId: '1:113551519405:web:be580f6d1254c4ac1aa024',
    messagingSenderId: '113551519405',
    projectId: 'elbisikleta-5ffd8',
    authDomain: 'elbisikleta-5ffd8.firebaseapp.com',
    storageBucket: 'elbisikleta-5ffd8.firebasestorage.app',
    measurementId: 'G-P60Z24TE16',
  );
}
